project_id = "lqmcokwbqnjuufcvodos"

[functions.dialogflow-chat]
verify_jwt = false

[functions.process-relworx-payment]
verify_jwt = false

[functions.mm-deposit]
verify_jwt = false

[functions.request-payment-status]
verify_jwt = false

[functions.send-payment-status]
verify_jwt = false

[functions.public-chat]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.send-agent-message]
verify_jwt = true

[functions.process-wallet-transaction-unified]
verify_jwt = true
